Config = {}

---------------------------------
-- settings
---------------------------------
Config.Keybind = 'J' -- keybind prompt to open shop
Config.UseNPCs = false -- enable NPC spawning at shop locations
Config.ZoneTarget = true
Config.NPCModel = 's_m_m_unibutchers_01' -- default NPC model for shops

---------------------------------
-- shop items

-- amount: default stock (remove to enable unlimited stock)
-- buyPrice: enables selling items to shop
-- maxStock: limits how much items players can sell to shop
-- minQuality: minimum quality that can be sold to shop (default 1)
-- restock: amount of items to be restocked per restock cycle

-- example: { name = 'bread', amount = 50, price = 0.10, buyPrice = 0.05, maxStock = 100, minQuality = 50, restock = 10 },
---------------------------------
Config.Products = {
    ['normal'] = {
        { name = 'notebook',               price = string.format("%.2f", 0.20),  buyPrice = string.format("%.2f", 10.00) },
        { name = 'pen',               price = string.format("%.2f", 0.20),  buyPrice = string.format("%.2f", 1.00) },
        -- Consumables
        { name = 'bread',               price = string.format("%.2f", 0.20),  buyPrice = string.format("%.2f", 0.05) },
        { name = 'coffee',              price = string.format("%.2f", 0.25),  buyPrice = string.format("%.2f", 0.06) },
        { name = 'canned_apricots',     price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.12) },
        { name = 'water',               price = string.format("%.2f", 0.10),  buyPrice = string.format("%.2f", 0.02) },
        { name = 'beef_jerky',          price = string.format("%.2f", 0.25),  buyPrice = string.format("%.2f", 0.06) },
        { name = 'canned_peaches',      price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.12) },
        { name = 'canned_pineapples',   price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.12) },
        { name = 'canned_beans',        price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.12) },
        { name = 'bag_candy',           price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", 0.25) },
        { name = 'chocolate_bar',       price = string.format("%.2f", 1.25),  buyPrice = string.format("%.2f", 0.32) },
        { name = 'cigar',               price = string.format("%.2f", 5),     buyPrice = string.format("%.2f", 1.25) },
        { name = 'cigarette',           price = string.format("%.2f", 1),  buyPrice = string.format("%.2f", 0.25) },
        -- Tools
        { name = 'canteen0',            price = string.format("%.2f", 10),    buyPrice = string.format("%.2f", 2.5) },
        { name = 'weapon_melee_lantern',price = string.format("%.2f", 50),    buyPrice = string.format("%.2f", 12.5) },
        { name = 'weapon_kit_binoculars',           price = string.format("%.2f", 100),   buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_kit_binoculars_improved',   price = string.format("%.2f", 500),   buyPrice = string.format("%.2f", 250) },
        { name = 'pet_food',               price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.10) },
    },
    ['weapons'] = {
        { name = 'weapon_revolver_cattleman',         price = string.format("%.2f", 40),    buyPrice = string.format("%.2f", 10.00) },
        { name = 'weapon_revolver_doubleaction',      price = string.format("%.2f", 30),    buyPrice = string.format("%.2f", 7.50) },
        { name = 'weapon_revolver_lemat',             price = string.format("%.2f", 100),   buyPrice = string.format("%.2f", 25.00) },
        { name = 'weapon_revolver_navy',              price = string.format("%.2f", 90),    buyPrice = string.format("%.2f", 22.50) },
        { name = 'weapon_revolver_schofield',         price = string.format("%.2f", 60),    buyPrice = string.format("%.2f", 15.00) },
        { name = 'weapon_pistol_mauser',              price = string.format("%.2f", 300),   buyPrice = string.format("%.2f", 75.00) },
        { name = 'weapon_pistol_semiauto',            price = string.format("%.2f", 270),   buyPrice = string.format("%.2f", 67.50) },
        { name = 'weapon_pistol_volcanic',            price = string.format("%.2f", 350),   buyPrice = string.format("%.2f", 87.50) },
        { name = 'weapon_rifle_boltaction',           price = string.format("%.2f", 480),    buyPrice = string.format("%.2f", 120) },
        { name = 'weapon_rifle_springfield',          price = string.format("%.2f", 420),    buyPrice = string.format("%.2f", 105) },
        { name = 'weapon_rifle_varmint',              price = string.format("%.2f", 140),    buyPrice = string.format("%.2f", 35) },
        { name = 'weapon_repeater_carbine',           price = string.format("%.2f", 145),    buyPrice = string.format("%.2f", 36.25) },
        { name = 'weapon_repeater_evans',             price = string.format("%.2f", 270),    buyPrice = string.format("%.2f", 67.50) },
        { name = 'weapon_repeater_winchester',        price = string.format("%.2f", 340),    buyPrice = string.format("%.2f", 85) },
        { name = 'weapon_repeater_henry',             price = string.format("%.2f", 385),    buyPrice = string.format("%.2f", 96.25) },
        { name = 'weapon_sniperrifle_rollingblock',   price = string.format("%.2f", 600),   buyPrice = string.format("%.2f", 150) },
        { name = 'weapon_sniperrifle_carcano',        price = string.format("%.2f", 800),   buyPrice = string.format("%.2f", 200) },
        { name = 'WEAPON_BOW',                        price = string.format("%.2f", 20),    buyPrice = string.format("%.2f", 5.00) },
        { name = 'ammo_box_revolver',                 price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_pistol',                   price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_rifle',                    price = string.format("%.2f", 5),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_repeater',                 price = string.format("%.2f", 2),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_shotgun',                  price = string.format("%.2f", 3),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_varmint',                  price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_arrow',                        price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", .25) },
        { name = 'weapon_repair_kit',                 price = string.format("%.2f", 2),     buyPrice = string.format("%.2f", 0.50) },
        { name = 'WEAPON_MELEE_KNIFE',                price = string.format("%.2f", 10),    buyPrice = string.format("%.2f", 2.50) },
        { name = 'weapon_lasso',                      price = string.format("%.2f", 20),    buyPrice = string.format("%.2f", 5.00) }
    },
    ['armoury'] = {
        { name = 'weapon_revolver_cattleman',  amount = 1, price = string.format("%.2f", 0) },
        { name = 'weapon_repeater_winchester', amount = 1, price = string.format("%.2f", 0) },
        { name = 'ammo_box_revolver',          amount = 10, price = string.format("%.2f", 0) },
        { name = 'ammo_box_repeater',          amount = 10, price = string.format("%.2f", 0) }
    },
    ['prison'] = {
        { name = 'bread', price = string.format("%.2f", 0) },
        { name = 'water', price = string.format("%.2f", 0) }
    },
    ['medic'] = {
        { name = 'bandage',  amount = 50, price = string.format("%.2f", 0) },
        { name = 'firstaid', amount = 50, price = string.format("%.2f", 0) },
		{ name = 'syringe', amount = 50, price = string.format("%.2f", 0) }
    },
    ['doctor'] = {
        { name = 'bandage',  amount = 50, price = string.format("%.2f", 5) },
		{ name = 'syringe', amount = 50, price = string.format("%.2f", 20) }
    },
    ['butcher'] = {
        -- Meats, trophies, and other parts
        { name = 'h_feather', amount = 0, buyPrice = string.format("%.2f", 0.05) },
        { name = 'h_meat_reptile', amount = 0, buyPrice = string.format("%.2f", 0.25) },
        { name = 'h_meat_bird', amount = 0, buyPrice = string.format("%.2f", 0.10) },
        { name = 'h_meat_small_game', amount = 0, buyPrice = string.format("%.2f", 0.10) },
        { name = 'h_meat_game', amount = 0, buyPrice = string.format("%.2f", 0.25) },
        { name = 'h_meat_big_game', amount = 0, buyPrice = string.format("%.2f", 0.75) },
        { name = 'h_meat_mutton', amount = 0, buyPrice = string.format("%.2f", 0.50) },
        { name = 'h_animal_fat', amount = 0, buyPrice = string.format("%.2f", 0.50) },
        { name = 'h_animal_heart', amount = 0, buyPrice = string.format("%.2f", 0.25) },
        { name = 'h_claw_animal', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_antler_buck', amount = 0, buyPrice = string.format("%.2f", 1.25) },
        { name = 'h_antler_elk', amount = 0, buyPrice = string.format("%.2f", 2.50) },
        { name = 'h_antler_moose', amount = 0, buyPrice = string.format("%.2f", 2.50) },
        { name = 'h_horn_animal', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_tusk_boar', amount = 0, buyPrice = string.format("%.2f", 0.50) },
        { name = 'h_wool', amount = 0, buyPrice = string.format("%.2f", 0.50) },
        { name = 'h_small_animal', amount = 0, buyPrice = string.format("%.2f", 1.00) },

        -- Pelts, hides, and skins
        { name = 'h_reptile_skin', amount = 0, buyPrice = 1.50},
        { name = 'h_hide_cow', amount = 0, buyPrice = 2.50},
        { name = 'h_pelt_badger', amount = 0, buyPrice = 1.00},
        { name = 'h_pelt_beaver', amount = 0, buyPrice = 1.50},
        { name = 'h_pelt_coyote', amount = 0, buyPrice = 1.50},
        { name = 'h_pelt_fox', amount = 0, buyPrice = 1.50},
        { name = 'h_pelt_muskrat', amount = 0, buyPrice = 1.00},
        { name = 'h_pelt_opossum', amount = 0, buyPrice = 1.00},
        { name = 'h_pelt_rabbit', amount = 0, buyPrice = 1.00},
        { name = 'h_pelt_raccoon', amount = 0, buyPrice = 1.00},
        { name = 'h_pelt_skunk', amount = 0, buyPrice = 1.00},
        { name = 'h_pelt_wolf', amount = 0, buyPrice = 3.00},
        { name = 'h_skin_alligator', amount = 0, buyPrice = 2.00},
        { name = 'h_skin_armadillo', amount = 0, buyPrice = 1.00},
        { name = 'h_skin_bear', amount = 0, buyPrice = 7.50},
        { name = 'h_skin_buck', amount = 0, buyPrice = 2.50},
        { name = 'h_skin_buffalo', amount = 0, buyPrice = 3.50},
        { name = 'h_skin_cougar', amount = 0, buyPrice = 7.50},
        { name = 'h_skin_deer', amount = 0, buyPrice = 2.00},
        { name = 'h_skin_iguana', amount = 0, buyPrice = 2.00},
        { name = 'h_skin_elk', amount = 0, buyPrice = 4.50},
        { name = 'h_skin_goat', amount = 0, buyPrice = 1.50},
        { name = 'h_skin_javelina_boar', amount = 0, buyPrice = 2.00},
        { name = 'h_skin_moose', amount = 0, buyPrice = 4.00},
        { name = 'h_skin_panther', amount = 0, buyPrice = 7.00},
        { name = 'h_skin_pig', amount = 0, buyPrice = 1.15},
        { name = 'h_skin_pronghorn', amount = 0, buyPrice = 1.75},
        { name = 'h_skin_ram', amount = 0, buyPrice = 2.00},
        { name = 'h_snake_skin', amount = 0, buyPrice = 1.50},

        -- Legendary pelts
        { name = 'h_pelt_beaver_legendary', amount = 0, buyPrice = string.format("%.2f", 20.00) },
        { name = 'h_pelt_coyote_legendary', amount = 0, buyPrice = string.format("%.2f", 30.00) },
        { name = 'h_pelt_fox_legendary', amount = 0, buyPrice = string.format("%.2f", 40.00) },
        { name = 'h_pelt_wolf_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },

        -- Legendary skins
        { name = 'h_skin_alligator_legendary', amount = 0, buyPrice = string.format("%.2f", 40.00) },
        { name = 'h_skin_bear_grizzly_legendary', amount = 0, buyPrice = string.format("%.2f", 60.00) },
        { name = 'h_skin_buck_legendary', amount = 0, buyPrice = string.format("%.2f", 30.00) },
        { name = 'h_skin_buffalo_legendary', amount = 0, buyPrice = string.format("%.2f", 30.00) },
        { name = 'h_skin_cougar_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_elk_legendary', amount = 0, buyPrice = string.format("%.2f", 40.00) },
        { name = 'h_skin_javelina_boar_legendary', amount = 0, buyPrice = string.format("%.2f", 30.00) },
        { name = 'h_skin_moose_legendary', amount = 0, buyPrice = string.format("%.2f", 40.00) },
        { name = 'h_skin_panther_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_ram_legendary', amount = 0, buyPrice = string.format("%.2f", 30.00) }, 
    },
    ['saloon'] = {
        { name = 'water', price = string.format("%.2f", 0.25)},
        { name = 'beer', price = string.format("%.2f", 1)},
        { name = 'whiskey', price = string.format("%.2f", 2)},
        { name = 'stew', price = string.format("%.2f", 0.50)},
        { name = 'fish_stew', price = string.format("%.2f", 0.60)},
        { name = 'bean_stew', price = string.format("%.2f", 0.40)},

    },
    ['fence'] = {
		{ name = 'weapon_revolver_doubleaction_gambler', price = string.format("%.2f", 300), buyPrice = string.format("%.2f", 75.00) },
       	{ name = 'weapon_revolver_cattleman_mexican',    price = string.format("%.2f", 300), buyPrice = string.format("%.2f", 75.00) },
        { name = 'weapon_revolver_navy_crossover',       price = string.format("%.2f", 400), buyPrice = string.format("%.2f", 75.00) },
        { name = 'weapon_pistol_m1899',                  price = string.format("%.2f", 1000), buyPrice = string.format("%.2f", 250) },
        { name = 'weapon_rifle_elephant',                price = string.format("%.2f", 580), buyPrice = string.format("%.2f", 145)},
        { name = 'weapon_bow_improved',                  price = string.format("%.2f", 500), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_MELEE_CLEAVER',                 price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_MELEE_HATCHET',           		 price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_MELEE_HATCHET_HUNTER',          price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_MELEE_KNIFE_TRADER',            price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_knife_jawbone',           price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_knife_horror',            price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_knife_rustic',            price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_machete',                 price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_machete_zavala',          price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_machete_collector',       price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_torch',                   price = string.format("%.2f", 1), buyPrice = string.format("%.2f", .25) },
        { name = 'weapon_melee_davy_lantern',            price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_lantern_halloween',       price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'WEAPON_THROWN_THROWING_KNIVES',        price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_THROWN_TOMAHAWK',               price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'weapon_thrown_bolas',                  price = string.format("%.2f", 30), buyPrice = string.format("%.2f", 7.5) },
        { name = 'weapon_thrown_bolas_hawkmoth',         price = string.format("%.2f", 30), buyPrice = string.format("%.2f", 7.5) },
        { name = 'weapon_thrown_bolas_ironspiked',       price = string.format("%.2f", 30), buyPrice = string.format("%.2f", 7.5) },
        { name = 'weapon_thrown_bolas_intertwined',      price = string.format("%.2f", 30), buyPrice = string.format("%.2f", 7.5) },
        { name = 'ammo_arrow_fire',                      price = string.format("%.2f", 50), buyPrice = string.format("%.2f", 2.5) },
        { name = 'ammo_arrow_dynamite',                  price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 2.5) },
        { name = 'ammo_box_rifle_elephant',              price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'weapon_thrown_dynamite',               price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 's_ring',                               amount = 0, buyPrice = string.format("%.2f", 3) },
        { name = 's_wedding_ring',                       amount = 0, buyPrice = string.format("%.2f", 6) },
        { name = 's_earings',                            amount = 0, buyPrice = string.format("%.2f", 4) },
        { name = 's_necklace',                           amount = 0, buyPrice = string.format("%.2f", 5) },
        { name = 's_pocket_watch',                       amount = 0, buyPrice = string.format("%.2f", 10) },
        { name = 's_lucky_rabbit_foot',                  amount = 0, buyPrice = string.format("%.2f", 5) },
        { name = 's_gold_nugget',                        amount = 0, buyPrice = string.format("%.2f", 25) }
    },
    ['wagon'] = {
        { name = 'wood_log',    price = string.format("%.2f", 0.75), buyPrice = string.format("%.2f", 0.75)},
        { name = 'iron_parts',  price = string.format("%.2f", 3.0),  buyPrice = string.format("%.2f", 3.0)},
        { name = 'steel_plate', price = string.format("%.2f", 5.0),  buyPrice = string.format("%.2f", 5.0)},
        { name = 'wagon_wheel', price = string.format("%.2f", 1.0),  buyPrice = string.format("%.2f", 1.0)},
        { name = 'leather',     price = string.format("%.2f", 0.50), buyPrice = string.format("%.2f", 0.50)},
        { name = 'rope',        price = string.format("%.2f", 0.10), buyPrice = string.format("%.2f", 0.10)},
        { name = 'nails',       price = string.format("%.2f", 0.01), buyPrice = string.format("%.2f", 0.01)},
        { name = 'paint',       price = string.format("%.2f", 0.25), buyPrice = string.format("%.2f", 0.25)},
    },
}


---------------------------------
-- shop locations and blips

-- persistentStock (true/false): enables stock to persist over server restart
---------------------------------
Config.StoreLocations = {
    ---------------------------------
    -- general store
    ---------------------------------
    {
        label = 'Rhodes General Store',
        name = 'gen-rhodes',
        products = 'normal',
        shopcoords = vec3(1329.80, -1294.37, 77.02),
        npccoords = vec4(1329.80, -1294.37, 77.02, 60.72),
        npcmodel = 'u_m_m_rhdgenstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Valentine General Store',
        name = 'gen-valentine',
        products = 'normal',
        shopcoords = vec3(-324.14, 803.51, 117.88),
        npccoords = vec4(-324.14, 803.51, 117.88, 280.98),
        npcmodel = 'u_m_m_valgenstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Strawberry General Store',
        name = 'gen-strawberry',
        products = 'normal',
        shopcoords = vector3(-1789.78, -388.15, 160.33),
        npccoords = vec4(-1789.78, -388.15, 160.33, 65.43),
        npcmodel = 'u_m_m_strgenstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Saint Denis General Store',
        name = 'gen-stdenis',
        products = 'normal',
        shopcoords = vector3(2825.7566, -1318.3192, 46.7557),
        npccoords = vector4(2824.863, -1319.74, 46.755, -39.61),
        npcmodel = 'u_m_m_nbxgeneralstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed General Store',
        name = 'gen-tumbleweed',
        products = 'normal',
        shopcoords = vec3(-5486.04, -2937.99, -0.40),
        npccoords = vec4(-5486.04, -2937.99, -0.40, 131.21),
        npcmodel = 's_m_m_unibutchers_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Armadillo General Store',
        name = 'gen-armadillo',
        products = 'normal',
        shopcoords = vec3(-3687.35, -2623.34, -13.43),
        npccoords = vec4(-3687.35, -2623.34, -13.43, 276.71),
        npcmodel = 'u_m_m_armgeneralstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Blackwater General Store',
        name = 'gen-blackwater',
        products = 'normal',
        shopcoords = vec3(-784.77, -1322.15, 43.88),
        npccoords = vec4(-784.77, -1322.15, 43.88, 194.64),
        npcmodel = 'u_m_o_blwgeneralstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Van Horn General Store',
        name = 'gen-vanhorn',
        products = 'normal',
        shopcoords = vector3(3025.60, 562.29, 44.72),
        npccoords = vec4(3025.60, 562.29, 44.72, 262.32),
        npcmodel = 's_m_m_unibutchers_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    ---------------------------------
    -- gunsmith
    ---------------------------------
    {
        label = 'Valentine Gunsmith',
        name = 'wep-valentine',
        products = 'weapons',
        shopcoords = vector3(-281.17, 778.94, 119.50),
        npccoords = vec4(-281.17, 778.94, 119.50, 0.59),
        npcmodel = 'u_m_m_valgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed Gunsmith',
        name = 'wep-tumbleweed',
        products = 'weapons',
        shopcoords = vec3(-5506.41, -2963.95, -0.64),
        npccoords = vec4(-5506.41, -2963.95, -0.64, 110.02),
        npcmodel = 'u_m_m_tumgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Saint Denis Gunsmith',
        name = 'wep-stdenis',
        products = 'weapons',
        shopcoords = vec3(2717.14, -1286.90, 49.64),
        npccoords = vec4(2717.14, -1286.90, 49.64, 29.91),
        npcmodel = 'u_m_m_nbxgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Gunsmith',
        name = 'wep-rhodes',
        products = 'weapons',
        shopcoords = vec3(1322.31, -1323.02, 77.89),
        npccoords = vec4(1322.31, -1323.02, 77.89, 354.88),
        npcmodel = 'u_m_m_rhdgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Annesburg Gunsmith',
        name = 'wep-annesburg',
        products = 'weapons',
        shopcoords = vector3(2948.42, 1319.44, 44.82),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    ---------------------------------
    -- saloon
    ---------------------------------
    {
        label = 'Blackwater Saloon',
        name = 'blk-saloon',
        products = 'saloon',
        shopcoords = vec3(-817.69, -1319.29, 43.68),
        npccoords = vec4(-817.69, -1319.29, 43.68, 281.47),
        npcmodel = 'u_m_o_blwbartender_01',
        scenario = 'WORLD_HUMAN_BARTENDER_CLEAN_GLASS',
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Valentine Saloon',
        name = 'val-saloon',
        products = 'saloon',
        shopcoords = vec3(-313.44, 806.14, 118.98),
        npccoords = vec4(-313.44, 806.14, 118.98, 283.74),
        npcmodel = 'u_m_o_blwbartender_01',
        scenario = 'WORLD_HUMAN_BARTENDER_CLEAN_GLASS',
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'La Bastille Saloon',
        name = 'lab-saloon',
        products = 'saloon',
        shopcoords = vec3(2639.87, -1226.13, 53.38),
        npccoords = vec4(2639.87, -1226.13, 53.38, 90.83),
        npcmodel = 'u_m_o_blwbartender_01',
        scenario = 'WORLD_HUMAN_BARTENDER_CLEAN_GLASS',
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Saloon',
        name = 'rho-saloon',
        products = 'saloon',
        shopcoords = vec3(1340.25, -1374.71, 80.48),
        npccoords = vec4(1340.25, -1374.71, 80.48, 260.32),
        npcmodel = 'u_m_o_blwbartender_01',
        scenario = 'WORLD_HUMAN_BARTENDER_CLEAN_GLASS',
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Old Light Saloon',
        name = 'old-saloon',
        products = 'saloon',
        shopcoords = vec3(2948.17, 528.08, 45.34),
        npccoords = vec4(2948.17, 528.08, 45.34, 182.96),
        npcmodel = 'u_m_o_blwbartender_01',
        scenario = 'WORLD_HUMAN_BARTENDER_CLEAN_GLASS',
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed Saloon',
        name = 'tumble-saloon',
        products = 'saloon',
        shopcoords = vec3(-5518.50, -2906.52, -1.75),
        npccoords = vec4(-5518.50, -2906.52, -1.75, 216.14),
        npcmodel = 'u_m_o_blwbartender_01',
        scenario = 'WORLD_HUMAN_BARTENDER_CLEAN_GLASS',
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    ---------------------------------
    -- Fences
    ---------------------------------
    {
        label = 'Thieves Landing Fence',
        name = 'Fence-Thieves',
        products = 'fence',
        shopcoords = vector3(-1403.17, -2317.91, 43.61),
        npccoords = vector4(-1402.01, -2318.32, 43.61, 67.8),
        blipsprite = 'blip_shop_shady_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Emerald Ranch Fence',
        name = 'Fence-Emerald',
        products = 'fence',
        shopcoords = vector3(1417.63, 271.68, 89.52),
        npccoords = vector4(1417.05, 273.53, 89.48, 203.7),
        blipsprite = 'blip_shop_shady_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Fence',
        name = 'Fence-Rhodes',
        products = 'fence',
        shopcoords = vector3(1320.5156, -1142.0728, 82.3542),
        npccoords = vector4(1319.4647, -1142.0039, 82.4087, 250.7928),
        blipsprite = 'blip_shop_shady_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Saint Denis Fence',
        name = 'Fence-StDenis',
        products = 'fence',
        shopcoords = vector3(2859.88, -1200.6, 49.59),
        npccoords = vector4(2859.55, -1202.18, 49.59, 18.3),
        blipsprite = 'blip_shop_shady_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    ---------------------------------
    -- Doctors
    ---------------------------------
    {
        label = 'Saint Denis Doctor',
        name = 'Doctor-StDenis',
        products = 'doctor',
        shopcoords = vector3(2719.5349, -1231.8680, 50.3672),
        npccoords = vector4(2721.3455, -1231.9725, 50.3678, 85.5629),
        blipsprite = 'blip_shop_doctor',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Doctor',
        name = 'Doctor-Rhodes',
        products = 'doctor',
        shopcoords = vector3(1370.2817, -1307.4030, 77.9710),
        npccoords = vector4(1369.1144, -1306.4569, 77.9710, 235.6972),
        blipsprite = 'blip_shop_doctor',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Valentine Doctor',
        name = 'Doctor-Valentine',
        products = 'doctor',
        shopcoords = vector3(-286.2402, 804.5875, 119.3859),
        npccoords = vector4(-288.0410, 804.1488, 119.3859, 276.7783),
        blipsprite = 'blip_shop_doctor',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Armadillo Doctor',
        name = 'Doctor-Armadillo',
        products = 'doctor',
        shopcoords = vector3(-3662.2378, -2597.3672, -13.3095),
        npccoords = vector4(-3662.6106, -2595.7751, -13.3095, 179.2983),
        blipsprite = 'blip_shop_doctor',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    ---------------------------------
    -- butcher
    ---------------------------------
    {
        label = 'Valentine Butcher',
        name = 'butcher-valentine',
        products = 'butcher',
        shopcoords = vector3(-341.05, 767.33, 116.70),
        npccoords = vector4(-339.26, 767.7, 116.57, 103.16),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'St Denis Butcher',
        name = 'butcher-stdenis',
        products = 'butcher',
        shopcoords = vector3(2816.37, -1322.24, 46.61),
        npccoords = vector4(2817.6848, -1323.25, 46.607814, 54.587085),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Butcher',
        name = 'butcher-rhodes',
        products = 'butcher',
        shopcoords = vector3(1296.36, -1279.26, 75.84),
        npccoords = vector4(1297.3735, -1277.661, 75.876304, 158.4201),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Annesburg Butcher',
        name = 'butcher-annesburg',
        products = 'butcher',
        shopcoords = vector3(2932.49, 1301.95, 44.48),
        npccoords = vector4(2934.1706, 1301.2891, 44.483638, 78.346809),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed Butcher',
        name = 'butcher-tumbleweed',
        products = 'butcher',
        shopcoords = vector3(-5508.10, -2947.73, -1.87),
        npccoords = vector4(-5509.831, -2947.271, -1.89185, 256.48596),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Blackwater Butcher',
        name = 'butcher-blackwater',
        products = 'butcher',
        shopcoords = vector3(-751.102, -1284.896, 43.276576),
        npccoords = vector4(-753.0086, -1284.84, 43.470008, 267.18395),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Strawberry Butcher',
        name = 'butcher-strawberry',
        products = 'butcher',
        shopcoords = vector3(-1752.91, -394.74, 156.19),
        npccoords = vector4(-1753.137, -392.8364, 156.24348, 189.32403),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Van Horn Butcher',
        name = 'butcher-vanhorn',
        products = 'butcher',
        shopcoords = vector3(2994.23, 571.79, 44.35),
        npccoords = vector4(2992.4711, 572.20001, 44.365322, 263.94104),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },

    ---------------------------------
    -- wagon merchants
    ---------------------------------
    {
        label = 'Valentine Wagon Parts',
        name = 'wagonparts-valentine',
        products = 'wagon',
        shopcoords = vector3(-242.42, 696.51, 113.46),
        npccoords = vector4(-242.42, 696.51, 113.46, 340.26),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = false,
        persistentStock = false,
    },
    {
        label = 'Rhodes Wagon Parts',
        name = 'wagonparts-rhodes',
        products = 'wagon',
        shopcoords = vector3(1467.68, -1373.22, 78.79),
        npccoords = vector4(1467.68, -1373.22, 78.79, 249.50),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = false,
        persistentStock = false,
    },
    {
        label = 'Saint Denis Wagon Parts',
        name = 'wagonparts-saintdenis',
        products = 'wagon',
        shopcoords = vector3(2695.47, -870.45, 42.47),
        npccoords = vector4(2695.47, -870.45, 42.47, 22.0),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = false,
        persistentStock = false,
    },
    {
        label = 'Blackwater Wagon Parts',
        name = 'wagonparts-blackwater',
        products = 'wagon',
        shopcoords = vector3(-868.94, -1380.57, 43.65),
        npccoords = vector4(-868.94, -1380.57, 43.65, 180.44),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = false,
        persistentStock = false,
    },
    {
        label = 'Strawberry Wagon Parts',
        name = 'wagonparts-strawberry',
        products = 'wagon',
        shopcoords = vector3(-1826.29, -570.82, 156.05),
        npccoords = vector4(-1826.29, -570.82, 156.05, 161.84),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = false,
        persistentStock = false,
    },
    {
        label = 'Armadillo Wagon Parts',
        name = 'wagonparts-armadillo',
        products = 'wagon',
        shopcoords = vector3(-3681.45, -2565.50, -13.51),
        npccoords = vector4(-3681.45, -2565.50, -13.51, 167.90),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = false,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed Wagon Parts',
        name = 'wagonparts-tumbleweed',
        products = 'wagon',
        shopcoords = vector3(-5524.76, -3055.89, -2.22),
        npccoords = vector4(-5524.76, -3055.89, -2.22, 144.41),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = false,
        persistentStock = false,
    },
}

