Config = {}

---------------------------------
-- settings
---------------------------------
Config.Keybind = 'J' -- keybind prompt to open shop
Config.UseNPCs = false -- enable NPC spawning at shop locations
Config.NPCModel = 's_m_m_unibutchers_01' -- default NPC model for shops

---------------------------------
-- shop items

-- amount: default stock (remove to enable unlimited stock)
-- buyPrice: enables selling items to shop
-- maxStock: limits how much items players can sell to shop
-- minQuality: minimum quality that can be sold to shop (default 1)
-- restock: amount of items to be restocked per restock cycle

-- example: { name = 'bread', amount = 50, price = string.format("%.2f", 0.10), buyPrice = string.format("%.2f", 0.05), maxStock = 100, minQuality = 50, restock = 10 },
---------------------------------
Config.Products = {
    ['normal'] = {
        -- Consumables
        { name = 'bread',               price = string.format("%.2f", 0.20),  buyPrice = string.format("%.2f", 0.05) },
        { name = 'coffee',              price = string.format("%.2f", 0.25),  buyPrice = string.format("%.2f", 0.06) },
        { name = 'canned_apricots',     price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.12) },
        { name = 'water',               price = string.format("%.2f", 0.10),  buyPrice = string.format("%.2f", 0.02) },
        { name = 'beef_jerky',          price = string.format("%.2f", 0.25),  buyPrice = string.format("%.2f", 0.06) },
        { name = 'canned_peaches',      price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.12) },
        { name = 'canned_pineapples',   price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.12) },
        { name = 'canned_beans',        price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.12) },
        { name = 'bag_candy',           price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", 0.25) },
        { name = 'chocolate_bar',       price = string.format("%.2f", 1.25),  buyPrice = string.format("%.2f", 0.32) },
        { name = 'cigar',               price = string.format("%.2f", 5),     buyPrice = string.format("%.2f", 1.25) },
        { name = 'cigarette',           price = string.format("%.2f", 1),  buyPrice = string.format("%.2f", 0.25) },
        -- Tools
        { name = 'canteen0',            price = string.format("%.2f", 10),    buyPrice = string.format("%.2f", 2.5) },
        { name = 'weapon_melee_lantern',price = string.format("%.2f", 50),    buyPrice = string.format("%.2f", 12.5) },
        { name = 'weapon_kit_binoculars',           price = string.format("%.2f", 100),   buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_kit_binoculars_improved',   price = string.format("%.2f", 500),   buyPrice = string.format("%.2f", 250) },
        { name = 'pet_food',               price = string.format("%.2f", 0.50),  buyPrice = string.format("%.2f", 0.10) },
        { name = 'bounty_book',               price = string.format("%.2f", 50.00),  buyPrice = string.format("%.2f", 50.00) },
    },
    ['weapons'] = {
        { name = 'weapon_revolver_cattleman',         price = string.format("%.2f", 40),    buyPrice = string.format("%.2f", 10.00) },
        { name = 'weapon_revolver_doubleaction',      price = string.format("%.2f", 30),    buyPrice = string.format("%.2f", 7.50) },
        { name = 'weapon_revolver_lemat',             price = string.format("%.2f", 100),   buyPrice = string.format("%.2f", 25.00) },
        { name = 'weapon_revolver_navy',              price = string.format("%.2f", 90),    buyPrice = string.format("%.2f", 22.50) },
        { name = 'weapon_revolver_schofield',         price = string.format("%.2f", 60),    buyPrice = string.format("%.2f", 15.00) },
        { name = 'weapon_pistol_mauser',              price = string.format("%.2f", 300),   buyPrice = string.format("%.2f", 75.00) },
        { name = 'weapon_pistol_semiauto',            price = string.format("%.2f", 270),   buyPrice = string.format("%.2f", 67.50) },
        { name = 'weapon_pistol_volcanic',            price = string.format("%.2f", 350),   buyPrice = string.format("%.2f", 87.50) },
        { name = 'weapon_rifle_boltaction',           price = string.format("%.2f", 480),    buyPrice = string.format("%.2f", 120) },
        { name = 'weapon_rifle_springfield',          price = string.format("%.2f", 420),    buyPrice = string.format("%.2f", 105) },
        { name = 'weapon_rifle_varmint',              price = string.format("%.2f", 140),    buyPrice = string.format("%.2f", 35) },
        { name = 'weapon_repeater_carbine',           price = string.format("%.2f", 145),    buyPrice = string.format("%.2f", 36.25) },
        { name = 'weapon_repeater_evans',             price = string.format("%.2f", 270),    buyPrice = string.format("%.2f", 67.50) },
        { name = 'weapon_repeater_winchester',        price = string.format("%.2f", 340),    buyPrice = string.format("%.2f", 85) },
        { name = 'weapon_repeater_henry',             price = string.format("%.2f", 385),    buyPrice = string.format("%.2f", 96.25) },
        { name = 'weapon_sniperrifle_rollingblock',   price = string.format("%.2f", 600),   buyPrice = string.format("%.2f", 150) },
        { name = 'weapon_sniperrifle_carcano',        price = string.format("%.2f", 800),   buyPrice = string.format("%.2f", 200) },
        { name = 'WEAPON_BOW',                        price = string.format("%.2f", 20),    buyPrice = string.format("%.2f", 5.00) },
        { name = 'ammo_box_revolver',                 price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_pistol',                   price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_rifle',                    price = string.format("%.2f", 5),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_repeater',                 price = string.format("%.2f", 2),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_shotgun',                  price = string.format("%.2f", 3),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_box_varmint',                  price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", .25) },
        { name = 'ammo_arrow',                        price = string.format("%.2f", 1),     buyPrice = string.format("%.2f", .25) },
        { name = 'weapon_repair_kit',                 price = string.format("%.2f", 2),     buyPrice = string.format("%.2f", 0.50) },
        { name = 'WEAPON_MELEE_KNIFE',                price = string.format("%.2f", 10),    buyPrice = string.format("%.2f", 2.50) },
        { name = 'weapon_lasso',                      price = string.format("%.2f", 20),    buyPrice = string.format("%.2f", 5.00) }
    },
    ['armoury'] = {
        { name = 'weapon_revolver_cattleman',  amount = 1, price = string.format("%.2f", 0) },
        { name = 'weapon_repeater_winchester', amount = 1, price = string.format("%.2f", 0) },
        { name = 'ammo_box_revolver',          amount = 10, price = string.format("%.2f", 0) },
        { name = 'ammo_box_repeater',          amount = 10, price = string.format("%.2f", 0) }
    },
    ['prison'] = {
        { name = 'bread', price = string.format("%.2f", 0) },
        { name = 'water', price = string.format("%.2f", 0) }
    },
    ['medic'] = {
        { name = 'bandage',  amount = 50, price = string.format("%.2f", 0) },
        { name = 'firstaid', amount = 50, price = string.format("%.2f", 0) },
		{ name = 'syringe', amount = 50, price = string.format("%.2f", 0) }
    },
    ['doctor'] = {
        { name = 'bandage',  amount = 50, price = string.format("%.2f", 5) },
		{ name = 'syringe', amount = 50, price = string.format("%.2f", 20) }
    },
    ['butcher'] = {
        { name = 'h_small_pelt', amount = 0, buyPrice = string.format("%.2f", 1) },
        { name = 'h_medium_pelt', amount = 0, buyPrice = string.format("%.2f", 3) },
        { name = 'h_large_pelt', amount = 0, buyPrice = string.format("%.2f", 5) },
        { name = 'h_feather', amount = 0, buyPrice = string.format("%.2f", 0.1) },
        { name = 'h_reptile_skin', amount = 0, buyPrice = string.format("%.2f", 2) },
        { name = 'h_turtle_shell', amount = 0, buyPrice = string.format("%.2f", 3) },
        { name = 'h_legendary_pelt', amount = 0, buyPrice = string.format("%.2f", 200) },
        { name = 'h_wool', amount = 0, buyPrice = string.format("%.2f", 2) },
        { name = 'h_meat_reptile', amount = 0, buyPrice = string.format("%.2f", 1) },
        { name = 'h_meat_bird', amount = 0, buyPrice = string.format("%.2f", 1) },
        { name = 'h_meat_small_game', amount = 0, buyPrice = string.format("%.2f", 1.75) },
        { name = 'h_meat_game', amount = 0, buyPrice = string.format("%.2f", 2.50) },
        { name = 'h_meat_big_game', amount = 0, buyPrice = string.format("%.2f", 3) },
        { name = 'h_meat_mutton', amount = 0, buyPrice = string.format("%.2f", 4) },
        { name = 'h_animal_fat', amount = 0, buyPrice = string.format("%.2f", 2) },
        { name = 'h_animal_heart', amount = 0, buyPrice = string.format("%.2f", 2) },
        { name = 'h_animal_trophy', amount = 0, buyPrice = string.format("%.2f", 1) }
    },
    ['bar'] = {
        { name = 'water', price = string.format("%.2f", 0.25)},
        { name = 'beer', price = string.format("%.2f", 1)},
        { name = 'whiskey', price = string.format("%.2f", 2)},
        { name = 'beef_stew', price = string.format("%.2f", 0.50)},
        { name = 'fish_stew', price = string.format("%.2f", 0.60)}
    },
    ['fence'] = {
		{ name = 'weapon_revolver_doubleaction_gambler', price = string.format("%.2f", 300), buyPrice = string.format("%.2f", 75.00) },
       	{ name = 'weapon_revolver_cattleman_mexican',    price = string.format("%.2f", 300), buyPrice = string.format("%.2f", 75.00) },
        { name = 'weapon_revolver_navy_crossover',       price = string.format("%.2f", 400), buyPrice = string.format("%.2f", 75.00) },
        { name = 'weapon_pistol_m1899',                  price = string.format("%.2f", 1000), buyPrice = string.format("%.2f", 250) },
        { name = 'weapon_rifle_elephant',                price = string.format("%.2f", 580), buyPrice = string.format("%.2f", 145)},
        { name = 'weapon_bow_improved',                  price = string.format("%.2f", 500), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_MELEE_CLEAVER',                 price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_MELEE_HATCHET',           		 price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_MELEE_HATCHET_HUNTER',          price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_MELEE_KNIFE_TRADER',            price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_knife_jawbone',           price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_knife_horror',            price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_knife_rustic',            price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_machete',                 price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_machete_zavala',          price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_machete_collector',       price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_torch',                   price = string.format("%.2f", 1), buyPrice = string.format("%.2f", .25) },
        { name = 'weapon_melee_davy_lantern',            price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'weapon_melee_lantern_halloween',       price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 25) },
        { name = 'WEAPON_THROWN_THROWING_KNIVES',        price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'WEAPON_THROWN_TOMAHAWK',               price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'weapon_thrown_bolas',                  price = string.format("%.2f", 30), buyPrice = string.format("%.2f", 7.5) },
        { name = 'weapon_thrown_bolas_hawkmoth',         price = string.format("%.2f", 30), buyPrice = string.format("%.2f", 7.5) },
        { name = 'weapon_thrown_bolas_ironspiked',       price = string.format("%.2f", 30), buyPrice = string.format("%.2f", 7.5) },
        { name = 'weapon_thrown_bolas_intertwined',      price = string.format("%.2f", 30), buyPrice = string.format("%.2f", 7.5) },
        { name = 'ammo_arrow_fire',                      price = string.format("%.2f", 50), buyPrice = string.format("%.2f", 2.5) },
        { name = 'ammo_arrow_dynamite',                  price = string.format("%.2f", 100), buyPrice = string.format("%.2f", 2.5) },
        { name = 'ammo_box_rifle_elephant',              price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 'weapon_thrown_dynamite',               price = string.format("%.2f", 10), buyPrice = string.format("%.2f", 2.5) },
        { name = 's_ring',                               amount = 0, buyPrice = string.format("%.2f", 3) },
        { name = 's_wedding_ring',                       amount = 0, buyPrice = string.format("%.2f", 6) },
        { name = 's_earings',                            amount = 0, buyPrice = string.format("%.2f", 4) },
        { name = 's_necklace',                           amount = 0, buyPrice = string.format("%.2f", 5) },
        { name = 's_pocket_watch',                       amount = 0, buyPrice = string.format("%.2f", 10) },
        { name = 's_lucky_rabbit_foot',                  amount = 0, buyPrice = string.format("%.2f", 5) },
        { name = 's_gold_nugget',                        amount = 0, buyPrice = string.format("%.2f", 25) }
    }
}

---------------------------------
-- shop locations and blips

-- persistentStock (true/false): enables stock to persist over server restart
---------------------------------
Config.StoreLocations = {
    ---------------------------------
    -- general store
    ---------------------------------
    {
        label = 'Rhodes General Store',
        name = 'gen-rhodes',
        products = 'normal',
        shopcoords = vector3(1328.99, -1293.28, 77.02 -0.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Valentine General Store',
        name = 'gen-valentine',
        products = 'normal',
        shopcoords = vector3(-322.433, 803.797, 117.882 -0.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Strawberry General Store',
        name = 'gen-strawberry',
        products = 'normal',
        shopcoords = vector3(-1791.49, -386.87, 160.33 -0.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	--[[
    {
        label = 'Annesburg General Store',
        name = 'gen-annesburg',
        products = 'normal',
        shopcoords = vector3(2931.35, 1365.94, 45.19 -0.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	--]]
    {
        label = 'Saint Denis General Store',
        name = 'gen-stdenis',
        products = 'normal',
        shopcoords = vector3(2826.13, -1318.6, 46.75 -.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed General Store',
        name = 'gen-tumbleweed',
        products = 'normal',
        shopcoords = vector3(-5487.613, -2938.54, -0.38 -0.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Armadillo General Store',
        name = 'gen-armadillo',
        products = 'normal',
        shopcoords = vector3(-3685.56, -2622.59, -13.43 -0.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Blackwater General Store',
        name = 'gen-blackwater',
        products = 'normal',
        shopcoords = vector3(-785.18, -1323.83, 43.88 -0.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Van Horn General Store',
        name = 'gen-vanhorn',
        products = 'normal',
        shopcoords = vector3(3027.03, 561.00, 44.72 -0.8),
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    ---------------------------------
    -- gunsmith
    ---------------------------------
    {
        label = 'Valentine Gunsmith',
        name = 'wep-valentine',
        products = 'weapons',
        shopcoords = vector3(-281.24, 780.71, 119.53),
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed Gunsmith',
        name = 'wep-tumbleweed',
        products = 'weapons',
        shopcoords = vector3(-5508.18, -2964.27, -0.63),
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Saint Denis Gunsmith',
        name = 'wep-stdenis',
        products = 'weapons',
        shopcoords = vector3(2716.42, -1285.42, 49.63),
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Gunsmith',
        name = 'wep-rhodes',
        products = 'weapons',
        shopcoords = vector3(1322.75, -1321.47, 77.89),
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Annesburg Gunsmith',
        name = 'wep-annesburg',
        products = 'weapons',
        shopcoords = vector3(2946.50, 1319.53, 44.82),
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    ---------------------------------
    -- butcher
    ---------------------------------
    {
        label = 'Valentine Butcher',
        name = 'butcher-valentine',
        products = 'butcher',
        shopcoords = vector3(-341.05, 767.33, 116.70),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'St Denis Butcher',
        name = 'butcher-stdenis',
        products = 'butcher',
        shopcoords = vector3(2816.37, -1322.24, 46.61),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Butcher',
        name = 'butcher-rhodes',
        products = 'butcher',
        shopcoords = vector3(1296.36, -1279.26, 75.84),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Annesburg Butcher',
        name = 'butcher-annesburg',
        products = 'butcher',
        shopcoords = vector3(2932.49, 1301.95, 44.48),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed Butcher',
        name = 'butcher-tumbleweed',
        products = 'butcher',
        shopcoords = vector3(-5508.10, -2947.73, -1.87),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Blackwater Butcher',
        name = 'butcher-blackwater',
        products = 'butcher',
        shopcoords = vector3(-751.102, -1284.896, 43.276576),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Strawberry Butcher',
        name = 'butcher-strawberry',
        products = 'butcher',
        shopcoords = vector3(-1752.91, -394.74, 156.19),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Van Horn Butcher',
        name = 'butcher-vanhorn',
        products = 'butcher',
        shopcoords = vector3(2994.23, 571.79, 44.35),
        blipsprite = 'blip_shop_butcher',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },

    ---------------------------------
    -- Bars
    ---------------------------------
    {
        label = "Smithfield's Saloon",
        name = 'Saloon-Valentine1',
        products = 'bar',
        shopcoords = vector3(-311.45, 806.11, 118.97),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = "Keane's Saloon",
        name = 'Saloon-Valentine2',
        products = 'bar',
        shopcoords = vector3(-240.57, 769.73, 118.08),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Armadillo Saloon',
        name = 'Saloon-Armadillo',
        products = 'bar',
        shopcoords = vector3(-3701.44, -2595.77, -13.32),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Blackwater Saloon',
        name = 'Saloon-Blackwater',
        products = 'bar',
        shopcoords = vector3(-815.75, -1318.44, 43.67),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = "Doyle's Tavern",
        name = 'Saloon-StDenis1',
        products = 'bar',
        shopcoords = vector3(2794.09, -1168.61, 47.92),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Bastille Saloon',
        name = 'Saloon-StDenis2',
        products = 'bar',
        shopcoords = vector3(2637.67, -1224.67, 53.38),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Old Light Saloon',
        name = 'Saloon-VanHorn',
        products = 'bar',
        shopcoords = vector3(2947.84, 526.27, 45.32),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed Saloon',
        name = 'Saloon-Tumbleweed',
        products = 'bar',
        shopcoords = vector3(-5517.68, -2907.94, -1.76),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Parlour House',
        name = 'Saloon-Rhodes',
        products = 'bar',
        shopcoords = vector3(1339.09, -1377.1, 80.48),
        blipsprite = 'blip_saloon',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },

    ---------------------------------
    -- Fences
    ---------------------------------
    {
        label = 'Thieves Landing Fence',
        name = 'Fence-Thieves',
        products = 'fence',
        shopcoords = vector3(-1403.17, -2317.91, 43.61),
        blipsprite = 'blip_shop_shady_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Emerald Ranch Fence',
        name = 'Fence-Emerald',
        products = 'fence',
        shopcoords = vector3(1417.63, 271.68, 89.52),
        blipsprite = 'blip_shop_shady_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Fence',
        name = 'Fence-Rhodes',
        products = 'fence',
        shopcoords = vector3(1320.5156, -1142.0728, 82.3542),
        blipsprite = 'blip_shop_shady_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Saint Denis Fence',
        name = 'Fence-StDenis',
        products = 'fence',
        shopcoords = vector3(2859.88, -1200.6, 49.59),
        blipsprite = 'blip_shop_shady_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },


    -- Doctors
    {
        label = 'Saint Denis Doctor',
        name = 'Doctor-StDenis',
        products = 'doctor',
        shopcoords = vector3(2719.5349, -1231.8680, 50.3672),
        blipsprite = 'blip_shop_doctor',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Doctor',
        name = 'Doctor-Rhodes',
        products = 'doctor',
        shopcoords = vector3(1370.2817, -1307.4030, 77.9710),
        blipsprite = 'blip_shop_doctor',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Valentine Doctor',
        name = 'Doctor-Valentine',
        products = 'doctor',
        shopcoords = vector3(-286.2402, 804.5875, 119.3859),
        blipsprite = 'blip_shop_doctor',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Armadillo Doctor',
        name = 'Doctor-Armadillo',
        products = 'doctor',
        shopcoords = vector3(-3662.2378, -2597.3672, -13.3095),
        blipsprite = 'blip_shop_doctor',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },

}
